services:
  app:
    image: rocky8-dev:latest # Use the Rocky 8 dev image
    volumes:
      - "${HOST_DEPENDENCIES}/rocky-8:/system_dependencies" # Mount system dependencies
    environment:
      - EASYBUILD_PREFIX=/apps/portable_application/rocky-8
      - EASYBUILD_MODULES_TOOL=Lmod
      - MODULEPATH=/apps/portable_application/rocky-8/modules
